version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
      
  
  nginx:
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf